### PR TITLE
Encoding error was fixed

### PR DESCRIPTION
**Pull request by HackoDev**
* encode function is used instead str()

### CODE REVIEW

**Comment by Guillaume-sousa** [comment]
Hi @HackoDev , thank you for your fix.

We just pushed the 'develop' branch for this package and moved your pull request to this branch. 
Could you please add a simple test case that validates your fix in the 'tests' folder?

Thank you,
Guillaume

**Comment by HackoDev** [comment]
Hi @Guillaume-sousa , sure. I will add a test for the fix.

**Comment by Guillaume-sousa** [comment]
Hi @HackoDev, we plan on adding your fix during the current run. Did you have a chance to look into the tests?

Thank you,
Guillaume

**Comment by HackoDev** [comment]
Hi @Guillaume-sousa , sorry for delayed answer. I've added tests for this fix.

**Pull request merged**
